skip docs package
Don't know why it broke.

/build/src/linux-5.18.1/Documentation/core-api/kernel-api:81: ./lib/bitmap.c:580: ERROR: Unexpected indentation.

Exception occurred:
  File "/usr/lib/python3.10/site-packages/docutils/nodes.py", line 654, in __getitem__
    return self.children[key]
IndexError: list index out of range
The full traceback has been saved in /tmp/sphinx-err-xavvvqk_.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[1]: *** [Documentation/Makefile:96: htmldocs] Error 2
make: *** [Makefile:1678: htmldocs] Error 2